import { supabase, watchAuth } from "./supabase.js";
const $=id=>document.getElementById(id);let dashboard={students:[],recentAttempts:[]};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
function message(text){const e=$("adminMessage");if(!e)return;e.textContent=text;e.classList.add("show");clearTimeout(message.t);message.t=setTimeout(()=>e.classList.remove("show"),4500);}
function renderStats(s){$("statStudents")&&( $("statStudents").textContent=s.students??0);$("statAttempts")&&( $("statAttempts").textContent=s.quizzesTaken??0);$("statPoints")&&( $("statPoints").textContent=s.pointsAwarded??0);$("statAnnouncements")&&( $("statAnnouncements").textContent=s.activeAnnouncements??0);}
function renderAttempts(){const el=$("recentAttempts");if(!el)return;if(!dashboard.recentAttempts.length){el.innerHTML='<div class="admin-empty">No quiz attempts yet.</div>';return;}el.innerHTML=`<table class="admin-table"><thead><tr><th>Student</th><th>Quiz</th><th>Score</th><th>Points</th><th>Completed</th></tr></thead><tbody>${dashboard.recentAttempts.map(a=>`<tr><td>${esc(a.studentName||"Student")}<br><small>${esc(a.registrationNumber)}</small></td><td>${esc(a.quizTitle)}</td><td>${a.score}/${a.totalQuestions}</td><td>${a.points}</td><td>${a.completedAt?new Date(a.completedAt).toLocaleString("en-NG"):"—"}</td></tr>`).join("")}</tbody></table>`;}
async function renderStudents(filter=""){const el=$("studentsTable");if(!el)return;const q=filter.toLowerCase();const rows=dashboard.students.filter(s=>!q||[s.fullName,s.email,s.registrationNumber,s.school,s.state].some(v=>String(v||"").toLowerCase().includes(q)));el.innerHTML=rows.length?`<table class="admin-table"><thead><tr><th>Student</th><th>Registration</th><th>School</th><th>Points</th><th>Quizzes</th><th>Status</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.fullName)}</strong><br><small>${esc(s.email)}</small></td><td>${esc(s.registrationNumber)}</td><td>${esc(s.school)}<br><small>${esc(s.state)}</small></td><td>${s.points??0}</td><td>${s.quizzesTaken??0}</td><td><button class="status-btn" data-student-id="${esc(s.id)}">${esc(s.status||"Active")}</button></td></tr>`).join("")}</tbody></table>`:'<div class="admin-empty">No matching students.</div>';
el.querySelectorAll("[data-student-id]").forEach(btn=>btn.addEventListener("click",async()=>{const s=dashboard.students.find(x=>x.id===btn.dataset.studentId);if(!s)return;const status=s.status==="Suspended"?"Active":"Suspended";btn.disabled=true;const{error}=await supabase.from("students").update({status}).eq("id",s.id);if(error){message(error.message);btn.disabled=false;return;}message("Student status updated.");await loadDashboard();}));}
function renderAnnouncements(){const el=$("announcementsList");if(!el)return;const{data}=dashboard;el.innerHTML=(data||[]).map(a=>`<article class="announcement-item"><strong>${esc(a.title)}</strong><p>${esc(a.body)}</p><small>${a.active?"Active":"Hidden"}</small><br><button class="status-btn" data-announcement-id="${a.id}">${a.active?"Hide":"Publish"}</button></article>`).join("")||'<div class="admin-empty">No announcements.</div>';el.querySelectorAll("[data-announcement-id]").forEach(b=>b.addEventListener("click",async()=>{const row=data.find(a=>a.id===b.dataset.announcementId);const{error}=await supabase.from("announcements").update({active:!row.active}).eq("id",row.id);if(error)return message(error.message);message("Announcement updated.");loadDashboard();}));}
async function loadDashboard(){try{const{data,error}=await supabase.rpc("get_admin_dashboard");if(error)throw error;dashboard=data;renderStats(data.stats||{});renderAttempts();renderStudents($("studentSearch")?.value||"");const{data:announcements}=await supabase.from("announcements").select("id,title,body,active,created_at").order("created_at",{ascending:false});dashboard.data=announcements||[];renderAnnouncements();}catch(error){console.error(error);message(error.message||"Unable to load admin dashboard.");}}
$("studentSearch")?.addEventListener("input",e=>renderStudents(e.target.value));
$("logoutButton")?.addEventListener("click",async()=>{await supabase.auth.signOut();location.href="auth.html";});
watchAuth(async user=>{if(!user)return location.href="auth.html";const{data:admin,error}=await supabase.rpc("is_admin");if(error||!admin)return location.href="dashboard.html";await loadDashboard();});
