import { auth, functions, watchAuth, firebaseSignOut, httpsCallable } from "./firebase.js";
const $=id=>document.getElementById(id);let dashboard={students:[],recentAttempts:[],announcements:[]};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const getAdminDashboard=httpsCallable(functions,"getAdminDashboard");
const setStudentStatus=httpsCallable(functions,"setStudentStatus");
const setAnnouncementStatus=httpsCallable(functions,"setAnnouncementStatus");
function message(text){const e=$("adminMessage");if(!e)return;e.textContent=text;e.classList.add("show");clearTimeout(message.t);message.t=setTimeout(()=>e.classList.remove("show"),4500);}
function renderStats(s){$("statStudents")&&($("statStudents").textContent=s.students??0);$("statAttempts")&&($("statAttempts").textContent=s.quizzesTaken??0);$("statPoints")&&($("statPoints").textContent=s.pointsAwarded??0);$("statAnnouncements")&&($("statAnnouncements").textContent=s.activeAnnouncements??0);}
function renderAttempts(){const el=$("recentAttempts");if(!el)return;if(!dashboard.recentAttempts.length){el.innerHTML='<div class="admin-empty">No quiz attempts yet.</div>';return;}el.innerHTML=`<table class="admin-table"><thead><tr><th>Student</th><th>Quiz</th><th>Score</th><th>Points</th><th>Completed</th></tr></thead><tbody>${dashboard.recentAttempts.map(a=>`<tr><td>${esc(a.studentName||"Student")}<br><small>${esc(a.registrationNumber)}</small></td><td>${esc(a.quizTitle)}</td><td>${a.score}/${a.total_questions||a.totalQuestions||0}</td><td>${a.points??0}</td><td>${a.completedAt?new Date(a.completedAt).toLocaleString("en-NG"):"—"}</td></tr>`).join("")}</tbody></table>`;}
async function renderStudents(filter=""){const el=$("studentsTable");if(!el)return;const q=filter.toLowerCase();const rows=dashboard.students.filter(s=>!q||[s.full_name,s.email,s.registration_number,s.school,s.state].some(v=>String(v||"").toLowerCase().includes(q)));el.innerHTML=rows.length?`<table class="admin-table"><thead><tr><th>Student</th><th>Registration</th><th>School</th><th>Points</th><th>Quizzes</th><th>Status</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.full_name)}</strong><br><small>${esc(s.email)}</small></td><td>${esc(s.registration_number)}</td><td>${esc(s.school)}<br><small>${esc(s.state)}</small></td><td>${s.points??0}</td><td>${s.quizzes_taken??0}</td><td><button class="status-btn" data-student-id="${esc(s.id)}">${esc(s.status||"Active")}</button></td></tr>`).join("")}</tbody></table>`:'<div class="admin-empty">No matching students.</div>';
el.querySelectorAll("[data-student-id]").forEach(btn=>btn.addEventListener("click",async()=>{const s=dashboard.students.find(x=>x.id===btn.dataset.studentId);if(!s)return;const status=s.status==="Suspended"?"active":"Suspended";btn.disabled=true;try{await setStudentStatus({studentId:s.id,status});message("Student status updated.");await loadDashboard();}catch(error){message(error.message||"Unable to update student status.");btn.disabled=false;}}));}
function renderAnnouncements(){const el=$("announcementsList");if(!el)return;const data=dashboard.announcements||[];el.innerHTML=data.map(a=>`<article class="announcement-item"><strong>${esc(a.title)}</strong><p>${esc(a.body)}</p><small>${a.active?"Active":"Hidden"}</small><br><button class="status-btn" data-announcement-id="${a.id}">${a.active?"Hide":"Publish"}</button></article>`).join("")||'<div class="admin-empty">No announcements.</div>';el.querySelectorAll("[data-announcement-id]").forEach(b=>b.addEventListener("click",async()=>{const row=data.find(a=>a.id===b.dataset.announcementId);if(!row)return;try{await setAnnouncementStatus({announcementId:row.id,active:!row.active});message("Announcement updated.");loadDashboard();}catch(error){message(error.message||"Unable to update announcement.");}}));}
async function loadDashboard(){try{const{data}=await getAdminDashboard();dashboard=data||{};renderStats(dashboard.stats||{});renderAttempts();renderStudents($("studentSearch")?.value||"");renderAnnouncements();}catch(error){console.error(error);message(error.message||"Unable to load admin dashboard.");}}
$("studentSearch")?.addEventListener("input",e=>renderStudents(e.target.value));
$("logoutButton")?.addEventListener("click",async()=>{await firebaseSignOut(auth);location.href="auth.html";});
watchAuth(async user=>{if(!user)return location.href="auth.html";await loadDashboard();});
