import { supabase } from "./supabase.js";
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
let state={quiz:null};
function msg(t){const e=$("adminMessage");if(e){e.textContent=t;e.classList.add("show");}}
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return location.href="auth.html";const{data,error}=await supabase.rpc("get_admin_dashboard");if(error){console.error(error);msg("Administrator access is required.");return;}state.quiz=data.quiz;$("statStudents").textContent=data.stats.students;$("statAttempts").textContent=data.stats.attempts;$("statPoints").textContent=data.stats.points;$("statAnnouncements").textContent=data.stats.announcements;renderAttempts(data.recentAttempts);renderStudents(data.students);if(data.quiz){$("quizTitle").value=data.quiz.title||"Daily Quiz";$("quizActive").checked=data.quiz.active!==false;} }
function renderAttempts(rows){const e=$("recentAttempts");if(!e)return;e.innerHTML=rows.map(r=>`<div class="admin-table-row"><strong>${esc(r.studentName)}</strong><span>${esc(r.registrationNumber)}</span><span>${esc(r.quizTitle)}</span><span>${r.score}/${r.totalQuestions}</span><span>${r.points} pts</span></div>`).join("")||"<p>No attempts yet.</p>";}
function renderStudents(rows){const e=$("studentsTable");if(!e)return;const render=list=>e.innerHTML=list.map(r=>`<div class="admin-table-row"><strong>${esc(r.fullName)}</strong><span>${esc(r.registrationNumber)}</span><span>${esc(r.school)}</span><span>${esc(r.state)}</span><span>${r.points} pts</span></div>`).join("")||"<p>No students yet.</p>";render(rows);$("studentSearch")?.addEventListener("input",ev=>{const q=ev.target.value.toLowerCase();render(rows.filter(r=>`${r.fullName} ${r.email} ${r.registrationNumber} ${r.school}`.toLowerCase().includes(q)));});}
document.querySelectorAll(".admin-tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-panel").forEach(x=>x.classList.remove("active"));t.classList.add("active");document.querySelector(`[data-panel="${t.dataset.tab}"]`)?.classList.add("active");}));
$("logoutButton")?.addEventListener("click",async()=>{await supabase.auth.signOut();location.href="auth.html";});$("rebuildStats")?.addEventListener("click",()=>load());
$("announcementForm")?.addEventListener("submit",async e=>{e.preventDefault();const title=$("announcementTitle").value.trim(),body=$("announcementBody").value.trim();if(!title||!body)return;const{error}=await supabase.from("announcements").insert({title,body,active:true});if(error)return msg(error.message);$("announcementForm").reset();await load();msg("Announcement published.");});
$("saveQuiz")?.addEventListener("click",async()=>{if(!state.quiz)return msg("Today's quiz configuration does not exist yet.");const{error}=await supabase.from("quiz_configs").update({title:$("quizTitle").value.trim()||"Daily Quiz",active:$("quizActive").checked}).eq("id",state.quiz.id);if(error)return msg(error.message);msg("Daily quiz saved.");});
load();
