import { supabase } from "./supabase.js";
const $=id=>document.getElementById(id);
function message(id,text,type="error"){const e=$(id);if(!e)return;e.textContent=text;e.className=`auth-message show ${type}`;}
function errorText(e){const m={"Invalid login credentials":"Incorrect email or password.","User already registered":"An account with this email already exists. Try logging in instead.","Email not confirmed":"Please verify your email address before logging in."};return m[e?.message]||e?.message||"Something went wrong. Please try again.";}
function busy(f,v){const b=f?.querySelector("button[type=submit]");if(b){b.disabled=v;b.setAttribute("aria-busy",String(v));}}
document.addEventListener("DOMContentLoaded",()=>{
 const signupPanel=$("signupPanel"),loginPanel=$("loginPanel");
 $("showLogin")?.addEventListener("click",()=>{signupPanel?.classList.remove("active");loginPanel?.classList.add("active")});
 $("showSignup")?.addEventListener("click",()=>{loginPanel?.classList.remove("active");signupPanel?.classList.add("active")});
 document.querySelectorAll(".password-toggle").forEach(b=>b.addEventListener("click",()=>{const i=$(b.dataset.target);if(i)i.type=i.type==="password"?"text":"password";}));
 $("signupForm")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,fullName=$("fullName")?.value.trim(),email=$("signupEmail")?.value.trim().toLowerCase(),phone=$("phone")?.value.trim(),school=$("school")?.value.trim(),state=$("state")?.value.trim(),password=$("signupPassword")?.value||"",confirm=$("confirmPassword")?.value||"";if(!fullName||!email||!phone||!school||!state)return message("signupMessage","Complete all registration fields.");if(password.length<8)return message("signupMessage","Password must be at least 8 characters.");if(password!==confirm)return message("signupMessage","Passwords do not match.");if(!$("terms")?.checked)return message("signupMessage","Accept the student guidelines to continue.");busy(f,true);try{const{data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName,phone,school,state}}});if(error)throw error;if(!data.user)throw new Error("Account could not be created.");if(!data.session){message("signupMessage","Account created. Check your email to verify your account, then log in.","success");return;}message("signupMessage","Account created. Redirecting…","success");location.replace("dashboard.html");}catch(error){console.error("Signup failed",error);message("signupMessage",errorText(error));}finally{busy(f,false);}});
 $("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,email=$("loginEmail")?.value.trim().toLowerCase(),password=$("loginPassword")?.value||"";if(!email||!password)return message("loginMessage","Enter your email and password.");busy(f,true);try{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;location.replace("dashboard.html");}catch(error){console.error(error);message("loginMessage",errorText(error));}finally{busy(f,false);}});
 $("forgotPassword")?.addEventListener("click",async e=>{e.preventDefault();const email=$("loginEmail")?.value.trim().toLowerCase();if(!email)return message("loginMessage","Enter your email first.");try{const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth.html`});if(error)throw error;message("loginMessage","Password reset instructions have been sent if the account exists.","success");}catch(error){message("loginMessage",errorText(error));}});
});
