import { supabase } from "./supabase.js";
const $=id=>document.getElementById(id), questionText=$("questionText"), answersContainer=$("answers"), questionNumber=$("questionNumber"), questionCounter=$("questionCounter"), progressBar=$("quizProgress"), nextButton=$("nextButton"), quizMessage=$("quizMessage");
let questions=[],currentQuestion=0,answers=[],submitting=false;
function showMessage(t){if(!quizMessage)return;quizMessage.textContent=t;quizMessage.classList.add("show");}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));}
function displayQuestion(){const q=questions[currentQuestion];if(!q)return;answersContainer.innerHTML="";questionText.textContent=q.question;questionNumber.textContent=String(currentQuestion+1).padStart(2,"0");questionCounter.textContent=`${currentQuestion+1} / ${questions.length}`;progressBar.style.width=`${((currentQuestion+1)/questions.length)*100}%`;nextButton.disabled=answers[currentQuestion]==null;nextButton.innerHTML=currentQuestion===questions.length-1?'Submit Quiz <i class="ri-check-line"></i>':'Next Question <i class="ri-arrow-right-line"></i>';q.answers.forEach((answer,index)=>{const b=document.createElement("button");b.type="button";b.className="answer-button";b.innerHTML=`<span class="answer-letter">${String.fromCharCode(65+index)}</span><span>${esc(answer)}</span>`;if(answers[currentQuestion]===index)b.classList.add("selected");b.onclick=()=>{answers[currentQuestion]=index;document.querySelectorAll(".answer-button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");nextButton.disabled=false;};answersContainer.appendChild(b);});}
async function start(){const{data:{user}}=await supabase.auth.getUser();if(!user)return location.replace("auth.html");try{const{data,error}=await supabase.rpc("get_daily_quiz");if(error)throw error;if(data.completed){showMessage("You have already completed today's Daily Quiz.");nextButton.disabled=true;return;}questions=data.questions||[];answers=new Array(questions.length).fill(null);if(!questions.length)throw new Error("No quiz is available today.");displayQuestion();}catch(e){console.error(e);showMessage(e.message||"Unable to load today's quiz.");nextButton.disabled=true;}}
nextButton?.addEventListener("click",async()=>{if(submitting||answers[currentQuestion]==null)return;if(currentQuestion<questions.length-1){currentQuestion++;displayQuestion();return;}submitting=true;nextButton.disabled=true;showMessage("Submitting your answers…");try{const{data,error}=await supabase.rpc("submit_daily_quiz",{p_answers:answers});if(error)throw error;localStorage.setItem("mlTriviaLastResult",JSON.stringify(data));location.replace("quiz-result.html");}catch(e){console.error(e);submitting=false;nextButton.disabled=false;showMessage(e.message||"Your quiz could not be submitted. Please try again.");}});
$("exitQuiz")?.addEventListener("click",()=>{if(!submitting)location.href="quiz.html";});start();
