import { auth, db, firebaseSignOut } from "../firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { collection, doc, getDoc, getDocs, limit, orderBy, query, where } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const $=id=>document.getElementById(id),message=$("dashboardMessage"),content=$("dashboardContent");
$("logoutButton")?.addEventListener("click",async()=>{await firebaseSignOut(auth);window.location.replace("../login.html");});
async function ensureStudentProfile(user){const ref=doc(db,"students",user.uid),snap=await getDoc(ref);if(snap.exists())return snap.data();throw new Error("student-profile-missing");}
async function loadDashboard(user){const student=await ensureStudentProfile(user);$("studentName").textContent=student.fullName||"Student";$("points").textContent=Number(student.leaguePoints||0).toLocaleString();$("quizzesTaken").textContent=Number(student.quizzesTaken||0);$("averageScore").textContent=`${Math.round(Number(student.averageAccuracy||0))}%`;
try{const higher=await getDocs(query(collection(db,"students"),where("status","==","active"),where("leaguePoints",">",Number(student.leaguePoints||0))));$("rank").textContent=`#${higher.size+1}`;}catch{$("rank").textContent="—";}
try{const quizSnap=await getDocs(query(collection(db,"quizzes"),where("status","==","live"),limit(1)));if(!quizSnap.empty){const d=quizSnap.docs[0],data=d.data();$("challengeTitle").textContent=data.title||"Live challenge";$("challengeMeta").textContent=`${data.questionCount||0} questions · ${Math.round(Number(data.durationSeconds||0)/60)||0} minutes`;const b=$("challengeButton");b.href=`quiz.html?id=${encodeURIComponent(d.id)}`;b.hidden=false;}}catch(error){console.warn("Live quiz lookup failed",error);}
try{const attempts=await getDocs(query(collection(db,"attempts"),where("studentId","==",user.uid),orderBy("submittedAt","desc"),limit(5)));const r=$("recentResults");if(!attempts.empty)r.innerHTML=attempts.docs.map(item=>{const d=item.data();return `<div class="result-item"><strong>${d.quizTitle||"Quiz"}</strong><span>${d.score??"Pending"}/${d.totalQuestions??"—"} · ${d.accuracy??"—"}%</span></div>`}).join("");}catch(error){console.warn("Recent results lookup failed",error);}
try{const announcements=await getDocs(query(collection(db,"announcements"),where("active","==",true),orderBy("publishedAt","desc"),limit(3)));const box=$("announcements");if(!announcements.empty)box.innerHTML=announcements.docs.map(item=>{const d=item.data();return `<div class="result-item"><strong>${d.title||"Announcement"}</strong><span>${d.body||""}</span></div>`}).join("");}catch(error){console.warn("Announcements lookup failed",error);}message.hidden=true;content.hidden=false;}
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../login.html");return;}try{await loadDashboard(user);}catch(error){console.error("Dashboard load failed",error);message.textContent=error.message==="student-profile-missing"?"Your student profile could not be found. Please register again.":"We couldn't load your dashboard. Please try again.";message.classList.add("error");message.hidden=false;content.hidden=true;}});
