import { auth, db } from "../firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { collection, doc, getDoc, getDocs, query, where, limit, orderBy, setDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),quizId=params.get("id");let questions=[],answers={},current=0,timerId=null,secondsLeft=0,attemptId=null;
function setState(text){$("quizState").textContent=text;$("quizState").hidden=false;$("quizArena").hidden=true;}
function renderQuestion(){const q=questions[current];$("questionCounter").textContent=`Question ${current+1} of ${questions.length}`;$("progressBar").style.width=`${((current+1)/questions.length)*100}%`;$("questionText").textContent=q.text;$("options").innerHTML=q.options.map((o,i)=>`<button type="button" class="option${answers[q.id]===i?" selected":""}" data-index="${i}"><span class="option-index">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join("");document.querySelectorAll(".option").forEach(b=>b.addEventListener("click",()=>{answers[q.id]=Number(b.dataset.index);renderQuestion();}));$("previousButton").disabled=current===0;$("nextButton").textContent=current===questions.length-1?"Submit quiz":"Next";}
function renderTimer(){const m=Math.floor(secondsLeft/60).toString().padStart(2,"0"),s=(secondsLeft%60).toString().padStart(2,"0");$("timer").textContent=`${m}:${s}`;$("timer").classList.toggle("warning",secondsLeft<=60);}
async function loadQuiz(){if(!quizId)throw new Error("quiz-not-selected");const snap=await getDoc(doc(db,"quizzes",quizId));if(!snap.exists()||snap.data().status!=="live")throw new Error("quiz-not-live");const qs=await getDocs(query(collection(db,"quizzes",quizId,"questions"),orderBy("order","asc")));$("quizTitle").textContent=snap.data().title||"Maths League Quiz";questions=qs.docs.map(d=>({id:d.id,...d.data()}));if(!questions.length)throw new Error("no-questions");secondsLeft=Number(snap.data().durationSeconds||600);}
async function startAttempt(user){const existing=await getDocs(query(collection(db,"attempts"),where("studentId","==",user.uid),where("quizId","==",quizId),where("status","==","in_progress"),limit(1)));if(!existing.empty){attemptId=existing.docs[0].id;return;}const ref=doc(collection(db,"attempts"));attemptId=ref.id;await setDoc(ref,{studentId:user.uid,quizId,status:"in_progress",startedAt:new Date().toISOString(),answers:{},createdAt:serverTimestamp()});}
async function submitQuiz(autoSubmitted=false){clearInterval(timerId);if(!attemptId){setState("We couldn't start your quiz attempt. Please return to the dashboard and try again.");return;}try{let score=0,possible=0;for(const q of questions){const p=Number(q.points??1);possible+=p;if(Number(answers[q.id])===Number(q.correctIndex))score+=p;}const accuracy=possible?Math.round(score/possible*100):0;await updateDoc(doc(db,"attempts",attemptId),{answers,score,possiblePoints:possible,accuracy,status:"submitted",submittedAt:serverTimestamp()});const user=auth.currentUser,studentRef=doc(db,"students",user.uid),studentSnap=await getDoc(studentRef);if(studentSnap.exists()){const s=studentSnap.data(),taken=Number(s.quizzesTaken||0)+1,avg=Math.round(((Number(s.averageAccuracy||0)*(taken-1))+accuracy)/taken),points=Number(s.leaguePoints||0)+score;await updateDoc(studentRef,{leaguePoints:points,quizzesTaken:taken,averageAccuracy:avg,updatedAt:serverTimestamp()});await setDoc(doc(db,"leaderboard",user.uid),{studentId:user.uid,displayName:s.fullName||"Student",school:s.school||"",leaguePoints:points,quizzesTaken:taken,averageAccuracy:avg,updatedAt:serverTimestamp()},{merge:true});}$("quizArena").hidden=true;$("quizState").hidden=true;$("quizComplete").hidden=false;$("completeMessage").textContent=autoSubmitted?`Time expired. Score: ${score}/${possible}.`:`Quiz submitted. Score: ${score}/${possible}.`;}catch(error){console.error("Quiz submission failed",error);setState(error?.message||"We couldn't submit your quiz. Please try again.");}}
$("previousButton")?.addEventListener("click",()=>{if(current>0){current--;renderQuestion();}});$("nextButton")?.addEventListener("click",()=>{if(current<questions.length-1){current++;renderQuestion();}else submitQuiz(false);});$("quitButton")?.addEventListener("click",()=>{if(confirm("Exit this quiz? Your current answers will not be submitted."))location.href="dashboard.html";});
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../login.html");return;}try{await loadQuiz();await startAttempt(user);$("quizState").hidden=true;$("quizArena").hidden=false;renderQuestion();renderTimer();timerId=setInterval(()=>{secondsLeft--;renderTimer();if(secondsLeft<=0)submitQuiz(true);},1000);}catch(error){console.error(error);setState(error.message==="quiz-not-selected"?"Choose a quiz from the dashboard first.":error.message==="quiz-not-live"?"This quiz is not currently live.":error.message==="no-questions"?"This quiz has no questions yet.":error.message||"We couldn't load this quiz. Please try again later.");}});
