import { auth, functions } from "../js/firebase.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js";
const $=id=>document.getElementById(id);let state={students:[],recentAttempts:[],announcements:[],quizzes:[]},selectedQuiz=null;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function err(e){console.error(e);$("error").textContent=e?.message||"Operation failed.";$("error").hidden=false;}
async function call(name,data={}){return(await httpsCallable(functions,name)(data)).data;}
async function load(){try{$("error").hidden=true;state=await call("getAdminDashboard");render();}catch(e){err(e)}}
function render(){const s=state.stats||{};$("stats").innerHTML=[["Students",s.students||0],["Quizzes completed",s.quizzesTaken||0],["Points awarded",s.pointsAwarded||0],["Active announcements",s.activeAnnouncements||0]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${esc(x[1])}</strong></div>`).join("");renderQuizzes();renderStudents();$("attempts").innerHTML=state.recentAttempts?.length?`<table class="table"><thead><tr><th>Student</th><th>Score</th><th>Accuracy</th><th>Status</th></tr></thead><tbody>${state.recentAttempts.map(a=>`<tr><td>${esc(a.studentName)}</td><td>${esc(a.score??0)}</td><td>${esc(a.accuracy??0)}%</td><td>${esc(a.status||"—")}</td></tr>`).join("")}</tbody></table>`:`<p class="muted">No attempts yet.</p>`;$("announcements").innerHTML=state.announcements?.length?state.announcements.map(a=>`<div class="card"><strong>${esc(a.title)}</strong><p>${esc(a.body)}</p><small class="muted">${a.active?"Active":"Inactive"}</small></div>`).join(""):`<p class="muted">No announcements yet.</p>`;}
function renderStudents(){const q=$("studentSearch").value.trim().toLowerCase(),items=(state.students||[]).filter(s=>!q||`${s.fullName} ${s.email} ${s.school}`.toLowerCase().includes(q));$("students").innerHTML=items.length?`<table class="table"><thead><tr><th>Name</th><th>School</th><th>Points</th><th>Status</th></tr></thead><tbody>${items.map(s=>`<tr><td>${esc(s.fullName)}</td><td>${esc(s.school)}</td><td>${esc(s.leaguePoints??0)}</td><td>${esc(s.status||"—")}</td></tr>`).join("")}</tbody></table>`:`<p class="muted">No students found.</p>`;}
function renderQuizzes(){const box=$("quizzes");if(!state.quizzes?.length){box.innerHTML='<p class="muted">No quizzes yet.</p>';return;}box.innerHTML=state.quizzes.map(q=>`<div class="card"><strong>${esc(q.title)}</strong><p>${esc(q.description||"")}</p><small class="muted">${esc(q.status)} · ${esc(q.questionCount||0)} questions · ${Math.round(Number(q.durationSeconds||600)/60)} min</small><div class="actions"><button data-action="question" data-id="${q.id}">Add question</button><button data-action="publish" data-id="${q.id}" data-status="${q.status==='live'?'closed':'live'}">${q.status==='live'?'Close':'Publish live'}</button></div></div>`).join("");box.querySelectorAll("button").forEach(b=>b.addEventListener("click",async()=>{try{const q=state.quizzes.find(x=>x.id===b.dataset.id);if(b.dataset.action==="question"){selectedQuiz=q;$("questionPanel").hidden=false;$("questionHeading").textContent=`Add question — ${q.title}`;$("questionOrder").value=Number(q.questionCount||0)+1;window.scrollTo({top:$("questionPanel").offsetTop-20,behavior:"smooth"});}else{await call("publishQuiz",{quizId:q.id,status:b.dataset.status});await load();}}catch(e){err(e)}}));}
$("quizForm").addEventListener("submit",async e=>{e.preventDefault();try{const r=await call("createQuiz",{title:$("quizTitle").value,description:$("quizDescription").value,durationSeconds:Number($("quizDuration").value)*60});e.target.reset();$("quizDuration").value=10;await load();selectedQuiz=state.quizzes.find(q=>q.id===r.id);$("questionPanel").hidden=false;$("questionHeading").textContent=`Add question — ${selectedQuiz.title}`;}catch(x){err(x)}});
$("questionForm").addEventListener("submit",async e=>{e.preventDefault();if(!selectedQuiz)return;try{const options=[...document.querySelectorAll(".optionInput")].map(x=>x.value.trim()).filter(Boolean);await call("upsertQuizQuestion",{quizId:selectedQuiz.id,text:$("questionText").value,options,correctIndex:Number($("correctIndex").value),points:Number($("questionPoints").value),order:Number($("questionOrder").value)});e.target.reset();$("questionPoints").value=1;selectedQuiz=state.quizzes.find(q=>q.id===selectedQuiz.id);$("questionOrder").value=Number(selectedQuiz?.questionCount||0)+1;await load();}catch(x){err(x)}});
$("closeQuestion").addEventListener("click",()=>$("questionPanel").hidden=true);$("studentSearch").addEventListener("input",renderStudents);$("refresh").addEventListener("click",load);$("logout").addEventListener("click",()=>signOut(auth));
$("announcementForm").addEventListener("submit",async e=>{e.preventDefault();try{await call("createAnnouncement",{title:$("announcementTitle").value,body:$("announcementBody").value});e.target.reset();await load();}catch(x){err(x)}});
onAuthStateChanged(auth,async user=>{if(!user){location.replace("../login.html");return;}await load();});
